"""initial schema

Revision ID: 47903d282ede
Revises:
Create Date: 2026-09-17 15:00:47.658306

Autogenerated on 2026-09-17 (against SQLModel.metadata), then hand-audited:

* ``op.create_table`` calls stay in dependency order (referenced tables first,
  FK children last).
* Non-unique indexes are created with ``unique=False``, unique ones with
  ``unique=True`` — no batch blocks: a batch rebuild only exists for ALTER
  rewrites on SQLite and this revision alters nothing.
* ``downgrade()`` reverses ``upgrade()``: FK children first, then parents.

The PostgreSQL dialect auto-quotes the reserved-word table ``user`` (it renders
``CREATE TABLE "user"``), so the same revision is portable to Neon without any
per-dialect special-casing here.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47903d282ede"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _create_core_tables() -> None:
    """Create every table that has no incoming foreign key."""
    op.create_table(
        "adcampaign",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("interval_hours", sa.Float(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repeat_count", sa.Integer(), nullable=False),
        sa.Column("max_repeats", sa.Integer(), nullable=False),
        sa.Column("next_run", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "adminlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analyticsevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_data", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "anonsession",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user1_id", sa.Integer(), nullable=False),
        sa.Column("user2_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "channelschedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("policy", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cloudfile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("remote_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documentchunk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chunk_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("embedding", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "engagementconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("frequency_minutes", sa.Integer(), nullable=False),
        sa.Column("last_engagement", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "forcejoinconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("channel_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("welcome_message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledgecache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "moderationconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("anti_spam", sa.Boolean(), nullable=False),
        sa.Column("anti_flood", sa.Boolean(), nullable=False),
        sa.Column("link_filter", sa.Boolean(), nullable=False),
        sa.Column("profanity_filter", sa.Boolean(), nullable=False),
        sa.Column("max_warnings", sa.Integer(), nullable=False),
        sa.Column("mute_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pendingapproval",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("change_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("auto_apply_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "personalityconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("personality", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("set_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quizscore",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("answered", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "referral",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("referrer_id", sa.Integer(), nullable=False),
        sa.Column("referee_id", sa.Integer(), nullable=False),
        sa.Column("referral_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reward_claimed", sa.Boolean(), nullable=False),
        sa.Column("xp_awarded", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "referralcode",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_referrals", sa.Integer(), nullable=False),
        sa.Column("successful_referrals", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reminder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("remind_at", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ``user`` is reserved in PostgreSQL; SQLAlchemy quotes it automatically.
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_allowed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "useractiveagent",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("agent_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("activated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "userlanguage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usermemory",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("interests", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("occupation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("personality_tags", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "userreputation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("reputation", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.Integer(), nullable=False),
        sa.Column("is_muted", sa.Boolean(), nullable=False),
        sa.Column("mute_until", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "userxp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("streak", sa.Integer(), nullable=False),
        sa.Column("last_daily", sa.DateTime(), nullable=True),
        sa.Column("achievements", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("referral_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "viralpost",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("viral_score", sa.Float(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "welcomemessage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def _create_fk_tables() -> None:
    """Create the tables that reference other tables via foreign keys."""
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("correlation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plan_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "toolrun",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("output_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"]),
        sa.PrimaryKeyConstraint("id"),
    )


# Non-unique indexes: (table, [(index_name, column), ...]).
_NON_UNIQUE_INDEXES: dict[str, list[tuple[str, str]]] = {
    "adcampaign": [
        ("ix_adcampaign_chat_id", "chat_id"),
        ("ix_adcampaign_status", "status"),
    ],
    "adminlog": [
        ("ix_adminlog_action", "action"),
        ("ix_adminlog_timestamp", "timestamp"),
        ("ix_adminlog_user_id", "user_id"),
    ],
    "analyticsevent": [
        ("ix_analyticsevent_chat_id", "chat_id"),
        ("ix_analyticsevent_created_at", "created_at"),
        ("ix_analyticsevent_event_type", "event_type"),
    ],
    "anonsession": [
        ("ix_anonsession_started_at", "started_at"),
        ("ix_anonsession_status", "status"),
        ("ix_anonsession_user1_id", "user1_id"),
        ("ix_anonsession_user2_id", "user2_id"),
    ],
    "channelschedule": [
        ("ix_channelschedule_chat_id", "chat_id"),
        ("ix_channelschedule_scheduled_at", "scheduled_at"),
        ("ix_channelschedule_status", "status"),
    ],
    "chat": [
        ("ix_chat_created_at", "created_at"),
        ("ix_chat_thread_id", "thread_id"),
    ],
    "documentchunk": [("ix_documentchunk_user_id", "user_id")],
    "knowledgecache": [
        ("ix_knowledgecache_expires_at", "expires_at"),
        ("ix_knowledgecache_query", "query"),
    ],
    "message": [
        ("ix_message_chat_id", "chat_id"),
        ("ix_message_correlation_id", "correlation_id"),
        ("ix_message_created_at", "created_at"),
        ("ix_message_role", "role"),
    ],
    "quizscore": [
        ("ix_quizscore_chat_id", "chat_id"),
        ("ix_quizscore_user_id", "user_id"),
    ],
    "referral": [
        ("ix_referral_referrer_id", "referrer_id"),
        ("ix_referral_referral_code", "referral_code"),
        ("ix_referral_status", "status"),
        ("ix_referral_created_at", "created_at"),
    ],
    "reminder": [
        ("ix_reminder_chat_id", "chat_id"),
        ("ix_reminder_remind_at", "remind_at"),
        ("ix_reminder_status", "status"),
        ("ix_reminder_user_id", "user_id"),
    ],
    "task": [
        ("ix_task_chat_id", "chat_id"),
        ("ix_task_completed_at", "completed_at"),
        ("ix_task_created_at", "created_at"),
        ("ix_task_status", "status"),
    ],
    "toolrun": [
        ("ix_toolrun_created_at", "created_at"),
        ("ix_toolrun_task_id", "task_id"),
        ("ix_toolrun_tool_name", "tool_name"),
    ],
    "user": [
        ("ix_user_created_at", "created_at"),
        ("ix_user_is_allowed", "is_allowed"),
    ],
    "userreputation": [
        ("ix_userreputation_chat_id", "chat_id"),
        ("ix_userreputation_user_id", "user_id"),
    ],
    "userxp": [
        ("ix_userxp_chat_id", "chat_id"),
        ("ix_userxp_user_id", "user_id"),
    ],
    "viralpost": [
        ("ix_viralpost_chat_id", "chat_id"),
        ("ix_viralpost_status", "status"),
    ],
}

# Unique indexes: (table, [(index_name, column), ...]).
_UNIQUE_INDEXES: dict[str, list[tuple[str, str]]] = {
    "chat": [("ix_chat_chat_id", "chat_id")],
    "engagementconfig": [("ix_engagementconfig_chat_id", "chat_id")],
    "forcejoinconfig": [("ix_forcejoinconfig_chat_id", "chat_id")],
    "moderationconfig": [("ix_moderationconfig_chat_id", "chat_id")],
    "personalityconfig": [("ix_personalityconfig_chat_id", "chat_id")],
    "referral": [("ix_referral_referee_id", "referee_id")],
    "referralcode": [
        ("ix_referralcode_user_id", "user_id"),
        ("ix_referralcode_code", "code"),
    ],
    "user": [("ix_user_telegram_id", "telegram_id")],
    "welcomemessage": [("ix_welcomemessage_chat_id", "chat_id")],
}


def _create_indexes() -> None:
    for table, indexes in _NON_UNIQUE_INDEXES.items():
        for name, column in indexes:
            op.create_index(name, table, [column], unique=False)
    for table, indexes in _UNIQUE_INDEXES.items():
        for name, column in indexes:
            op.create_index(name, table, [column], unique=True)


def upgrade() -> None:
    """Upgrade schema."""
    _create_core_tables()
    _create_fk_tables()
    _create_indexes()


def downgrade() -> None:
    """Downgrade schema: FK children first, then parents."""
    for table, indexes in reversed(_NON_UNIQUE_INDEXES.items()):
        for name, _ in reversed(indexes):
            op.drop_index(name, table_name=table)
    for table, indexes in reversed(list(_UNIQUE_INDEXES.items())):
        for name, _ in reversed(indexes):
            op.drop_index(name, table_name=table)

    op.drop_table("toolrun")
    op.drop_table("task")
    op.drop_table("message")
    op.drop_table("welcomemessage")
    op.drop_table("viralpost")
    op.drop_table("userxp")
    op.drop_table("userreputation")
    op.drop_table("usermemory")
    op.drop_table("userlanguage")
    op.drop_table("useractiveagent")
    op.drop_table("user")
    op.drop_table("reminder")
    op.drop_table("referralcode")
    op.drop_table("referral")
    op.drop_table("quizscore")
    op.drop_table("personalityconfig")
    op.drop_table("pendingapproval")
    op.drop_table("moderationconfig")
    op.drop_table("knowledgecache")
    op.drop_table("forcejoinconfig")
    op.drop_table("engagementconfig")
    op.drop_table("documentchunk")
    op.drop_table("cloudfile")
    op.drop_table("chat")
    op.drop_table("channelschedule")
    op.drop_table("anonsession")
    op.drop_table("analyticsevent")
    op.drop_table("adminlog")
    op.drop_table("adcampaign")
