"""Generated Markdown projections — outputs of the truth engine, never inputs.

Every page this module renders is a pure function of a freshly computed
projection.  ``tests/architecture/test_operation_truth_gate.py`` re-renders
from a fresh recomputation and requires byte equality with the committed
file, so editing a number (or a row, or a definition) by hand turns the gate
red until ``python -m nexus_ai_agent.nagar --docs`` regenerates it from the
sources.  Markdown never establishes truth for JSON here and JSON never
establishes truth for Markdown: both are projections of the recomputation.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from nexus_ai_agent.nagar import sources
from nexus_ai_agent.nagar.truth import LADDER, WAVES

HEADER = (
    "<!-- GENERATED by `python -m nexus_ai_agent.nagar --docs` from the live "
    "sources via OPERATION_TRUTH.json. DO NOT EDIT: edits are detected by "
    "tests/architecture/test_operation_truth_gate.py and turn CI red. -->"
)

# Generated pages live at the repository root (machine artifacts next to
# OPERATION_TRUTH.json): ``docs/README.md`` is the fenced shared index and is
# leased by another agent — adding files under ``docs/`` would force an edit
# there.  The index rows are recorded as deferred work in the audit report.
MATRIX_PATH = Path("OPERATION_CONTRACT_MATRIX.md")
MATURITY_PATH = Path("L0_L4_MATURITY.md")
RECONCILIATION_PATH = Path("RECONCILIATION.md")
WAVE_PLAN_PATH = Path("OPERATION_WAVE_PLAN.md")

GENERATED_DOCS = (MATRIX_PATH, MATURITY_PATH, RECONCILIATION_PATH, WAVE_PLAN_PATH)


def ux_modes(permission_level: str, status_flag: str) -> str:
    """Contract implication of the three product modes (no UI is built here).

    Rule (documented, mechanical): catalogue level ``A``/``B`` operations are
    consumable in all three modes (Conversation / Moment Guidance /
    Professional Manual); level ``C`` requires the Manual mode's explicit
    confirmation; runtime-only control operations without a catalogue row are
    recorded as moment+manual infrastructure.  This records *contract*
    implications only.
    """
    level = str(permission_level).upper()
    if status_flag == "RUNTIME_ONLY":
        return "moment+manual"
    if level == "C":
        return "manual"
    if level in {"A", "B"}:
        return "all three"
    return "all three"


def pack_class(node: dict[str, Any]) -> str:
    """BUILT-IN / LOCAL PACK / LOCAL PACK NEEDED — computed from the registrar."""
    registrar = node.get("registrar_pack", "NOT_AVAILABLE")
    if node.get("pipeline", {}).get("registry") != "PRESENT":
        return "LOCAL PACK NEEDED"
    if registrar.startswith("nexus_ai_agent."):
        return "BUILT-IN"
    return "LOCAL PACK"


def locality(node: dict[str, Any]) -> str:
    """Locality class: models ⇒ LOCAL_PREFERRED, else LOCAL_ONLY (no cloud ops)."""
    engine = str(node.get("identity", {}).get("engine_catalog", "")).lower()
    model_tokens = ("onnx", "model", "segmentation", "inpaint", "whisper", "pyannote", "aligner")
    if any(token in engine for token in model_tokens):
        return "LOCAL_PREFERRED"
    return "LOCAL_ONLY"


def _matrix_row(node: dict[str, Any]) -> str:
    pipeline = node["pipeline"]
    identity = node["identity"]
    stages = " | ".join(
        pipeline[stage]
        for stage in (
            "product",
            "contract",
            "registry",
            "capability",
            "surface",
            "command",
            "execution",
            "artifact",
            "proof",
        )
    )
    modes = ux_modes(identity["permission_level_catalog"], identity["status_flag"])
    return (
        f"| {node['operation_id']} | {identity['t_id']} | {identity['status_flag']} | "
        f"{stages} | {node['maturity']['token']} | {modes} | "
        f"{pack_class(node)} | {locality(node)} | {node['registrar_pack']} |"
    )


def render_matrix(projection: dict[str, Any]) -> str:
    recon = projection["reconciliation"]
    lines = [
        HEADER,
        "",
        "# Nagar Operation Contract Matrix",
        "",
        "Single source of this table: `python -m nexus_ai_agent.nagar` recomputing the",
        "nine-stage pipeline for every operation of the universe (catalogue ∪ runtime).",
        "Statuses: `MISSING` / `PARTIAL` (design-only or wired-unproven) / `PRESENT`",
        "(static fact) / `PROVEN` (backed by executable evidence).",
        "",
        f"Universe: **{recon['universe_count']}** operations — "
        f"catalogue {recon['catalog_count']}, runtime {recon['runtime_count']}, "
        f"overlap {recon['overlap_count']}, missing {recon['missing_count']}, "
        f"runtime-only {recon['runtime_only_count']}, "
        f"surface-reachable {recon['surface_count']}.",
        "",
        "| operation | id | flag | product | contract | registry | capability | "
        "| surface | command | execution | artifact | proof | L | UX modes | pack | "
        "| locality | registrar |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    lines.extend(_matrix_row(node) for node in projection["operations"])
    lines.extend(
        [
            "",
            "Runtime-only operations (registered, never in the catalogue) keep",
            "`product=MISSING` by design: they are real dispatchable code the product",
            "document does not yet name, not catalogue rows.",
            "",
        ]
    )
    return "\n".join(lines)


def render_maturity(projection: dict[str, Any]) -> str:
    distribution: dict[str, int] = {}
    for node in projection["operations"]:
        token = node["maturity"]["token"]
        distribution[token] = distribution.get(token, 0) + 1
    lines = [
        HEADER,
        "",
        "# Nagar L0–Maturity Matrix (canonical ladder)",
        "",
        "This page is rendered from the **single** ladder definition owned by",
        "`src/nexus_ai_agent/nagar/truth.py::LADDER`. The open pull requests defined",
        "`L3`/`L4` incompatibly; this is the resolution — no bare level token from any",
        "other document is portable here.",
        "",
        "## The ladder",
        "",
    ]
    for level in ("L0", "L1", "L2", "L3", "L4"):
        lines.append(f"* **{level}** — {LADDER[level]}")
    lines.extend(
        [
            "",
            f"**Why no L4 appears below:** {projection['l4_unavailable_reason']}",
            "",
            "## Distribution (recomputed, never stored)",
            "",
            "| level | count |",
            "|---|---|",
        ]
    )
    for level in ("L0", "L1", "L2", "L3", "L4"):
        lines.append(f"| {level} | {distribution.get(level, 0)} |")
    lines.extend(
        [
            "",
            "## Per-operation levels",
            "",
            "| level | operations |",
            "|---|---|",
        ]
    )
    for level in ("L0", "L1", "L2", "L3", "L4"):
        members = sorted(
            node["operation_id"]
            for node in projection["operations"]
            if node["maturity"]["token"] == level
        )
        rendered = ", ".join(f"`{op}`" for op in members) or "—"
        lines.append(f"| {level} ({len(members)}) | {rendered} |")
    lines.append("")
    return "\n".join(lines)


def render_reconciliation(projection: dict[str, Any]) -> str:
    recon = projection["reconciliation"]
    drift = projection.get("contract_drift") or []
    lines = [
        HEADER,
        "",
        "# Nagar Operation Reconciliation",
        "",
        "Set arithmetic over the live sources — `PRODUCT(catalogue) ∩/−/∪ REGISTRY`,",
        "recomputed on every run. No number on this page is hand-maintained.",
        "",
        "## Counts",
        "",
        "| quantity | value | rule |",
        "|---|---|---|",
        f"| product catalogue | {recon['catalog_count']} | rows of the pack tables "
        f"in `{sources.CATALOG_PATH}` |",
        f"| runtime registry | {recon['runtime_count']} | `build_runtime_registry()` |",
        f"| overlap | {recon['overlap_count']} | catalogue ∩ registry |",
        f"| missing | {recon['missing_count']} | catalogue − registry |",
        f"| runtime-only | {recon['runtime_only_count']} | registry − catalogue |",
        f"| universe | {recon['universe_count']} | catalogue ∪ registry |",
        f"| surface-reachable | {recon['surface_count']} | allow-list ∪ slideshow entrypoint |",
        f"| suite-executed | {recon['suite_executed_count']} | tests AST execution probe |",
        "",
        "## Missing (catalogue rows no registrar ships)",
        "",
    ]
    missing_by_category = recon.get("missing_by_category") or {}
    for category, count in sorted(missing_by_category.items()):
        lines.append(f"* `{category}` — {count}")
    lines.append("")
    for operation_id in recon["missing"]:
        lines.append(f"* `{operation_id}`")
    lines.extend(["", "## Runtime-only (dispatchable, never catalogued)", ""])
    runtime_only_by_category = recon.get("runtime_only_by_category") or {}
    for category, count in sorted(runtime_only_by_category.items()):
        lines.append(f"* `{category}` — {count}")
    lines.append("")
    for operation_id in recon["runtime_only"]:
        lines.append(f"* `{operation_id}`")
    lines.extend(["", "## Contract drift findings (mechanical)", ""])
    if not drift:
        lines.append("* none — the probes agree")
    for item in drift:
        if item.get("kind") == "ladder_vocabulary_fingerprints":
            continue
        lines.append(f"* `{item['kind']}` — {item['detail']}")
    lines.append("")
    return "\n".join(lines)


def render_wave_plan(projection: dict[str, Any]) -> str:
    missing_entries = projection.get("missing_set") or []
    edges = projection.get("dependency_edges") or []
    by_wave: dict[str, list[dict[str, Any]]] = {wave: [] for wave in WAVES}
    for entry in missing_entries:
        by_wave[entry["wave"]].append(entry)

    lines = [
        HEADER,
        "",
        "# Nagar Operation Wave Plan (computed missing set)",
        "",
        "The membership of every wave below is **recomputed** from",
        "`missing_set` in `OPERATION_TRUTH.json` (catalogue − registry), with the",
        "wave chosen by measured facts only: whether the catalogue's engine cell",
        "names a model, whether the pack already ships, the type-level dependency",
        "edges, and the catalogue permission level. Engineering order here is",
        "*not* product priority — prerequisites are explicit so neither can be",
        "smuggled in as the other.",
        "",
        "The universal per-wave prerequisite chain is:",
        "",
        "```",
        "contract (OperationSpec + input model)",
        "  -> runtime (handler + registrar wiring)",
        "  -> verifier (pack test + boundary test + truth recompute)",
        "  -> surface (entrypoint mapping, when the wave calls for one)",
        "  -> E2E (recorded proof entry in OPERATION_PROOF_REGISTRY.json)",
        "```",
        "",
        "`IMPLEMENTATION-BLOCKED` marks an operation whose contract cannot honestly",
        "start before its infrastructure prerequisite exists (a model lane, a pack",
        "manifest). Such an operation stays in the wave it is *blocked for* with the",
        "blocker named — it is never quietly moved earlier by a documentation edit.",
        "",
    ]

    wave_notes = {
        "NOW": (
            "**NOW** — no model required, the pack already ships, and no missing "
            "operation blocks it: only the operation itself (spec → handler → "
            "verifier) is missing. Lowest risk: existing pack substrate, existing "
            "lane, existing test conventions."
        ),
        "NEXT": (
            "**NEXT** — no model required, but the pack itself does not ship yet: "
            "manifest + registrar composition come before any operation work "
            "(pack-before-operation is the composition rule the runtime enforces)."
        ),
        "AFTER_VERTICAL_SLICE": (
            "**AFTER VERTICAL SLICE** — blocked on a family vertical slice: the "
            "model-dependent primitives other missing operations consume "
            "(output-type edges below), and the operations whose inputs come "
            "from those primitives even when they need no model themselves. Each "
            "primitive needs the model lane (fetch → hash → license → cache → "
            "offline run) first; the slice is proven end-to-end contract → "
            "runtime → verifier → E2E with a recorded proof before its "
            "dependents start."
        ),
        "POST_MVP": (
            "**POST-MVP** — model-dependent dependents/orphans below confirmation "
            "level: implement after the family primitive's slice is proven."
        ),
        "LATER": (
            "**LATER** — model-dependent and catalogue permission level C "
            "(confirmation-heavy identity semantics): the confirmation contract and "
            "the model lane must both be proven before design starts."
        ),
    }

    for wave in WAVES:
        entries = by_wave[wave]
        lines.append(f"## {wave} ({len(entries)} operations)")
        lines.append("")
        lines.append(wave_notes[wave])
        lines.append("")
        if not entries:
            lines.append("_No operation currently computes into this wave._")
            lines.append("")
            continue
        lines.append(
            "| operation | pack | dependency | lane | test requirement | locality "
            "| security | complexity | prerequisites |"
        )
        lines.append("|---|---|---|---|---|---|---|---|---|")
        for entry in entries:
            blocked = ""
            if entry["dependency"] == "model_runtime":
                blocked = " IMPLEMENTATION-BLOCKED: model lane (fetch/hash/license/cache)"
            elif not entry["pack_ships_today"]:
                blocked = f" IMPLEMENTATION-BLOCKED: pack {entry['pack_id']} must ship first"
            prereqs = f"contract -> runtime -> verifier -> surface -> E2E;{blocked}"
            lines.append(
                f"| `{entry['operation_id']}` | {entry['pack_id']} | "
                f"{entry['dependency']} | {entry['execution_lane']} | "
                f"`{entry['test_requirement']}` | {entry['locality']} | "
                f"{entry['security']} | {entry['complexity']} | {prereqs} |"
            )
        lines.append("")

    lines.extend(
        [
            "## Type-level dependency edges (catalogue Input → Output, mechanical)",
            "",
            "An edge `a -> b` exists when `b`'s input cell names a type `a`'s output",
            "cell produces. Renaming a type rewrites this graph; nothing is curated.",
            "",
            "| from | to | via types |",
            "|---|---|---|",
        ]
    )
    for edge in edges:
        lines.append(f"| `{edge['from']}` | `{edge['to']}` | {edge['via']} |")
    lines.append("")
    return "\n".join(lines)


RENDERERS = {
    MATRIX_PATH: render_matrix,
    MATURITY_PATH: render_maturity,
    RECONCILIATION_PATH: render_reconciliation,
    WAVE_PLAN_PATH: render_wave_plan,
}


def render_all(projection: dict[str, Any]) -> dict[Path, str]:
    return {path: renderer(projection) for path, renderer in RENDERERS.items()}


def write_docs(projection: dict[str, Any], root: Path | None = None) -> list[Path]:
    base = root if root is not None else sources.REPO_ROOT
    written: list[Path] = []
    for path, text in render_all(projection).items():
        target = base / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
        written.append(target)
    return written


__all__ = [
    "GENERATED_DOCS",
    "HEADER",
    "MATRIX_PATH",
    "MATURITY_PATH",
    "RECONCILIATION_PATH",
    "WAVE_PLAN_PATH",
    "render_all",
    "write_docs",
]
