"""Creative Intelligence Plane -- the layer that turns meaning into a plan.

This package owns one slice of the pipeline and nothing else:

``INTENT -> UNDERSTANDING -> STRATEGY -> TYPED CREATIVE IR -> COMPILATION ->
EXECUTABLE PLAN -> COMMAND BUS -> EXECUTION``

It owns the four boxes from ``INTENT`` to ``EXECUTABLE PLAN``. It does **not**
own the last two. Concretely, this package must never:

* execute anything -- no ``subprocess``, no file or network I/O;
* touch the CommandBus, ``PlanTransaction``, undo, locks or idempotency (owned
  by the Canonical Creative Execution Substrate);
* initialise storage, databases, backups or recovery (owned by the Persistent
  Recovery Substrate).

The plane *proposes*; authority to execute belongs elsewhere. The boundary is
enforced by ``tests/architecture/test_creative_intelligence_boundary.py``, which
fails the build on a forbidden import rather than trusting this docstring.

Current slice (task-224): :mod:`nexus_ai_agent.creative.intelligence.ir` -- the
Typed Creative IR. Later slices (semantic layer, deterministic compiler,
semantic revision, reference recipe) are defined against it, which is exactly
why it lands first.
"""

from __future__ import annotations

from nexus_ai_agent.creative.intelligence.diff import (
    AttentionChange,
    AudioChange,
    ConstraintChange,
    DiffLineage,
    DiffLineageError,
    EffectChange,
    IRDelta,
    IRDeltaEntry,
    IRDeltaKind,
    LineagePair,
    SceneChange,
    SemanticDiff,
    TextChange,
    TransitionChange,
    WorkDiff,
    diff_works,
)
from nexus_ai_agent.creative.intelligence.errors import (
    ConstraintViolationError,
    CreativeIRError,
    DanglingReferenceError,
    IdentityError,
    IRValidationError,
    RevisionAmbiguityError,
    RevisionError,
    RevisionTargetError,
    SemanticDiffError,
    SerializationError,
    TimingError,
    UnsupportedRevisionError,
)
from nexus_ai_agent.creative.intelligence.identity import (
    IR_VERSION,
    MICROSECONDS_PER_SECOND,
    IRVersion,
    canonical_json,
    content_id,
    sealed_id,
)
from nexus_ai_agent.creative.intelligence.ir import (
    Asset,
    AssetKind,
    AudioIntent,
    Constraint,
    ConstraintKind,
    ConstraintSpec,
    ConstraintTarget,
    CreativeBrief,
    CreativeWork,
    Effect,
    EffectFamily,
    EffectParam,
    EmphasisConstraint,
    ExclusionConstraint,
    Layer,
    LayerContent,
    MediaContent,
    NarrativeRole,
    OrderConstraint,
    Origin,
    OutputRequirement,
    PacingConstraint,
    Priority,
    QualityConstraint,
    Scene,
    Segment,
    SemanticRole,
    StyleIntent,
    TextContent,
    TextSpec,
    Timing,
    TimingConstraint,
    Track,
    Transition,
    TransitionKind,
    TypographicStyle,
    Violation,
    seal_work,
)
from nexus_ai_agent.creative.intelligence.revision import (
    AffectedNode,
    AudioIntentChange,
    ConstraintPacingChange,
    ConstraintQualityChange,
    ConstraintTimingChange,
    EffectIntentChange,
    NodeTarget,
    RevisionIntent,
    RevisionResult,
    RevisionTarget,
    SceneMetadataChange,
    SceneRoleTarget,
    SceneTimingChange,
    TextSpecChange,
    TransitionIntentChange,
    apply_revision,
)
from nexus_ai_agent.creative.intelligence.semantics import (
    DIRECTIVES,
    LEXICON,
    SemanticCollision,
    SemanticCollisionError,
    SemanticDirective,
    SemanticMeaning,
    SemanticResolution,
    SemanticResolutionError,
    StyleTarget,
    apply_semantics,
    detect_collisions,
    normalize_phrase,
    resolve_semantics,
)

__all__ = [
    "resolve_semantics",
    "normalize_phrase",
    "apply_semantics",
    "detect_collisions",
    "StyleTarget",
    "SemanticResolutionError",
    "SemanticResolution",
    "SemanticMeaning",
    "SemanticDirective",
    "SemanticCollisionError",
    "SemanticCollision",
    "DIRECTIVES",
    "LEXICON",
    "IR_VERSION",
    "IRVersion",
    "MICROSECONDS_PER_SECOND",
    "Asset",
    "AssetKind",
    "AudioIntent",
    "Constraint",
    "ConstraintKind",
    "ConstraintSpec",
    "ConstraintTarget",
    "ConstraintViolationError",
    "CreativeBrief",
    "CreativeIRError",
    "CreativeWork",
    "DanglingReferenceError",
    "DiffLineage",
    "DiffLineageError",
    "Effect",
    "EffectFamily",
    "EffectParam",
    "EmphasisConstraint",
    "ExclusionConstraint",
    "IRValidationError",
    "IdentityError",
    "Layer",
    "LayerContent",
    "MediaContent",
    "NarrativeRole",
    "OrderConstraint",
    "Origin",
    "PacingConstraint",
    "OutputRequirement",
    "Priority",
    "QualityConstraint",
    "Scene",
    "Segment",
    "SemanticRole",
    "SerializationError",
    "StyleIntent",
    "TextContent",
    "TextSpec",
    "Timing",
    "TimingConstraint",
    "TimingError",
    "Track",
    "Transition",
    "TransitionKind",
    "TypographicStyle",
    "Violation",
    "IRDeltaKind",
    "IRDeltaEntry",
    "IRDelta",
    "LineagePair",
    "SceneChange",
    "ConstraintChange",
    "TransitionChange",
    "TextChange",
    "AudioChange",
    "EffectChange",
    "AttentionChange",
    "SemanticDiff",
    "WorkDiff",
    "diff_works",
    "RevisionError",
    "RevisionTargetError",
    "RevisionAmbiguityError",
    "UnsupportedRevisionError",
    "SemanticDiffError",
    "NodeTarget",
    "SceneRoleTarget",
    "RevisionTarget",
    "SceneTimingChange",
    "SceneMetadataChange",
    "ConstraintTimingChange",
    "ConstraintPacingChange",
    "ConstraintQualityChange",
    "TextSpecChange",
    "TransitionIntentChange",
    "AudioIntentChange",
    "EffectIntentChange",
    "RevisionIntent",
    "AffectedNode",
    "RevisionResult",
    "apply_revision",
    "canonical_json",
    "content_id",
    "sealed_id",
    "seal_work",
]
