"""Typed Creative IR and semantic normalization boundary.

The package owns declarative meaning only: it has no command bus, executor,
filesystem authority, or storage authority. Strategy and orchestration consume
these existing models; the deterministic compiler remains in ``creative.spine``.
"""

from __future__ import annotations

from nexus_ai_agent.creative.intelligence.errors import (
    ConstraintViolationError,
    CreativeIRError,
    DanglingReferenceError,
    IdentityError,
    IRValidationError,
    SerializationError,
    TimingError,
)
from nexus_ai_agent.creative.intelligence.identity import (
    IR_VERSION,
    MICROSECONDS_PER_SECOND,
    IRVersion,
    canonical_json,
    content_id,
    sealed_id,
)
from nexus_ai_agent.creative.intelligence.ir import (
    Asset,
    AssetKind,
    AudioIntent,
    Constraint,
    ConstraintKind,
    ConstraintSpec,
    ConstraintTarget,
    CreativeBrief,
    CreativeWork,
    Effect,
    EffectFamily,
    EffectParam,
    EmphasisConstraint,
    ExclusionConstraint,
    Layer,
    LayerContent,
    MediaContent,
    NarrativeRole,
    OrderConstraint,
    Origin,
    OutputRequirement,
    PacingConstraint,
    Priority,
    QualityConstraint,
    Scene,
    Segment,
    SemanticRole,
    StyleIntent,
    TextContent,
    TextSpec,
    Timing,
    TimingConstraint,
    Track,
    Transition,
    TransitionKind,
    TypographicStyle,
    Violation,
    seal_work,
)
from nexus_ai_agent.creative.intelligence.semantics import (
    DIRECTIVES,
    LEXICON,
    SemanticCollision,
    SemanticCollisionError,
    SemanticDirective,
    SemanticMeaning,
    SemanticResolution,
    SemanticResolutionError,
    StyleTarget,
    apply_semantics,
    detect_collisions,
    normalize_phrase,
    resolve_semantics,
)

__all__ = [
    "Asset",
    "AssetKind",
    "AudioIntent",
    "Constraint",
    "ConstraintKind",
    "ConstraintSpec",
    "ConstraintTarget",
    "ConstraintViolationError",
    "CreativeBrief",
    "CreativeIRError",
    "CreativeWork",
    "DIRECTIVES",
    "DanglingReferenceError",
    "Effect",
    "EffectFamily",
    "EffectParam",
    "EmphasisConstraint",
    "ExclusionConstraint",
    "IdentityError",
    "IR_VERSION",
    "IRValidationError",
    "IRVersion",
    "LEXICON",
    "Layer",
    "LayerContent",
    "MICROSECONDS_PER_SECOND",
    "MediaContent",
    "NarrativeRole",
    "OrderConstraint",
    "Origin",
    "OutputRequirement",
    "PacingConstraint",
    "Priority",
    "QualityConstraint",
    "Scene",
    "Segment",
    "SemanticCollision",
    "SemanticCollisionError",
    "SemanticDirective",
    "SemanticMeaning",
    "SemanticResolution",
    "SemanticResolutionError",
    "SemanticRole",
    "SerializationError",
    "StyleIntent",
    "StyleTarget",
    "TextContent",
    "TextSpec",
    "Timing",
    "TimingConstraint",
    "TimingError",
    "Track",
    "Transition",
    "TransitionKind",
    "TypographicStyle",
    "Violation",
    "apply_semantics",
    "canonical_json",
    "content_id",
    "detect_collisions",
    "normalize_phrase",
    "resolve_semantics",
    "seal_work",
    "sealed_id",
]
