"""Nagar creative studio -- Creative Operating System core.

Owned by Agent 2 (Principal Creative Systems Engineer + Product UX Architect +
Media Pipeline Engineer + Interaction Designer).

A typed, UI-free command and interaction surface for the studio: state models,
hierarchical capability registry, semantic reference resolver, atomic command bus,
shared playhead cursor, moment guidance, range selection, Persian RTL subtitles,
and two-tier preview/master pipeline.
"""

from __future__ import annotations

from nexus_ai_agent.creative.studio.authorization import ProjectAccess, ProjectAuthorizer
from nexus_ai_agent.creative.studio.bus import CommandBus
from nexus_ai_agent.creative.studio.capabilities import (
    Capability,
    CapabilityDescription,
    CapabilityRegistry,
    Domain,
    OperationContext,
    OperationOutcome,
    OperationSpec,
    PermissionDecision,
    build_wave1_registry,
)
from nexus_ai_agent.creative.studio.engine import (
    RedoStackEmptyError,
    SessionSnapshot,
    StudioSession,
    create_studio_session,
)
from nexus_ai_agent.creative.studio.interaction import (
    CandidateMoment,
    CandidateMomentKind,
    ContextualResolver,
    GuidanceCard,
    GuidanceCardAvailability,
    GuidanceCardManager,
    MissingPackExperience,
    MissingPackReport,
    MomentGuidanceEngine,
    PlayheadCursorSource,
    RangeSelection,
    SharedPlayheadCursor,
    StudioAccessibility,
    StudioAction,
    StudioErgonomics,
)
from nexus_ai_agent.creative.studio.models import (
    COMMAND_SCHEMA_VERSION,
    LEGACY_SCHEMA_VERSION,
    PROTOCOL_VERSION,
    ActorIdentity,
    AssetRecord,
    AuthorizationError,
    CapabilityError,
    CapabilitySnapshot,
    CapabilityVersionError,
    Clip,
    CommandExecutionError,
    CommandProvenance,
    CommandResult,
    CommandValidationError,
    EditTransaction,
    EffectLayerRef,
    ExecutionPolicy,
    ExecutionPolicyError,
    IdempotencyConflictError,
    InputRef,
    InputReferenceError,
    Marker,
    MediaRef,
    NagarError,
    PermissionDeniedError,
    PermissionLevel,
    Playhead,
    PreconditionError,
    Project,
    ReferenceResolutionError,
    RequestContext,
    TimeBase,
    Timeline,
    TimeRangeUS,
    Track,
    TypedCommand,
    UndoStackEmptyError,
    UnknownCapabilityError,
    UnknownOperationError,
    compute_parameters_hash,
    compute_state_hash,
    frame_number_for,
    new_project,
)
from nexus_ai_agent.creative.studio.preview import (
    AudioWaveformSample,
    FidelityDiff,
    MasterProfile,
    PipelineMode,
    PreviewFrameData,
    PreviewPipelineEngine,
    PreviewProfile,
)
from nexus_ai_agent.creative.studio.references import (
    ReferenceExpr,
    ReferenceInput,
    ReferenceResolver,
)
from nexus_ai_agent.creative.studio.subtitles import (
    PersianRTLStyler,
    SubtitleCue,
    SubtitleTrack,
)

__all__ = [
    "COMMAND_SCHEMA_VERSION",
    "LEGACY_SCHEMA_VERSION",
    "PROTOCOL_VERSION",
    "ActorIdentity",
    "AssetRecord",
    "AudioWaveformSample",
    "AuthorizationError",
    "CandidateMoment",
    "CandidateMomentKind",
    "Capability",
    "CapabilityDescription",
    "CapabilityError",
    "CapabilityRegistry",
    "CapabilitySnapshot",
    "CapabilityVersionError",
    "Clip",
    "CommandBus",
    "CommandExecutionError",
    "CommandProvenance",
    "CommandResult",
    "CommandValidationError",
    "ContextualResolver",
    "Domain",
    "EditTransaction",
    "EffectLayerRef",
    "ExecutionPolicy",
    "ExecutionPolicyError",
    "FidelityDiff",
    "GuidanceCard",
    "GuidanceCardAvailability",
    "GuidanceCardManager",
    "IdempotencyConflictError",
    "InputRef",
    "InputReferenceError",
    "Marker",
    "MasterProfile",
    "MediaRef",
    "MissingPackExperience",
    "MissingPackReport",
    "MomentGuidanceEngine",
    "NagarError",
    "OperationContext",
    "OperationOutcome",
    "OperationSpec",
    "PermissionDecision",
    "PermissionDeniedError",
    "PermissionLevel",
    "PersianRTLStyler",
    "PipelineMode",
    "Playhead",
    "PlayheadCursorSource",
    "PreconditionError",
    "PreviewFrameData",
    "PreviewPipelineEngine",
    "PreviewProfile",
    "Project",
    "ProjectAccess",
    "ProjectAuthorizer",
    "RangeSelection",
    "RedoStackEmptyError",
    "ReferenceExpr",
    "ReferenceInput",
    "ReferenceResolutionError",
    "ReferenceResolver",
    "RequestContext",
    "SessionSnapshot",
    "SharedPlayheadCursor",
    "StudioAccessibility",
    "StudioAction",
    "StudioErgonomics",
    "StudioSession",
    "SubtitleCue",
    "SubtitleTrack",
    "TimeBase",
    "TimeRangeUS",
    "Timeline",
    "Track",
    "TypedCommand",
    "UndoStackEmptyError",
    "UnknownCapabilityError",
    "UnknownOperationError",
    "build_wave1_registry",
    "compute_parameters_hash",
    "compute_state_hash",
    "create_studio_session",
    "frame_number_for",
    "new_project",
]
