"""Nagar creative studio -- Wave 1: Green Cockpit core.

A typed, UI-free command surface for the studio: state models, the
hierarchical capability registry, the semantic reference resolver and the
atomic command bus.

Wave 1 guarantees:

* no React/DOM/Canvas -- input is a typed JSON command, output is an
  in-memory state update;
* no heavy dependencies (no torch/transformers/CV);
* no ``storage/`` or ``llm/`` imports from this package.
"""

from __future__ import annotations

from nexus_ai_agent.creative.studio.authorization import ProjectAccess, ProjectAuthorizer
from nexus_ai_agent.creative.studio.bus import CommandBus
from nexus_ai_agent.creative.studio.capabilities import (
    Capability,
    CapabilityDescription,
    CapabilityRegistry,
    Domain,
    OperationContext,
    OperationOutcome,
    OperationSpec,
    PermissionDecision,
    build_wave1_registry,
)
from nexus_ai_agent.creative.studio.models import (
    COMMAND_SCHEMA_VERSION,
    LEGACY_SCHEMA_VERSION,
    PROTOCOL_VERSION,
    ActorIdentity,
    AssetRecord,
    AuthorizationError,
    CapabilityError,
    CapabilitySnapshot,
    CapabilityVersionError,
    Clip,
    CommandExecutionError,
    CommandProvenance,
    CommandResult,
    CommandValidationError,
    EditTransaction,
    EffectLayerRef,
    ExecutionPolicy,
    ExecutionPolicyError,
    IdempotencyConflictError,
    InputRef,
    InputReferenceError,
    Marker,
    MediaRef,
    NagarError,
    PermissionDeniedError,
    PermissionLevel,
    PlanExecutionResult,
    PlanResult,
    PlanTransaction,
    Playhead,
    PreconditionError,
    Project,
    ReferenceResolutionError,
    RequestContext,
    TargetRef,
    TimeBase,
    Timeline,
    TimeRangeUS,
    Track,
    TypedCommand,
    UndoConflictError,
    UndoStackEmptyError,
    UnknownCapabilityError,
    UnknownOperationError,
    compute_parameters_hash,
    compute_state_hash,
    frame_number_for,
    new_project,
)
from nexus_ai_agent.creative.studio.passport import (
    ArtifactPassport,
    ExecutionProof,
    IndependentMediaVerificationError,
    ProvenanceCausalChain,
    verify_causal_provenance_chain,
    verify_media_artifact_independently,
)
from nexus_ai_agent.creative.studio.persistence import (
    DurableStore,
    DurableStudioStore,
    JobAttemptLease,
    LeaseExpiredError,
    StaleFencingTokenError,
)
from nexus_ai_agent.creative.studio.references import (
    ReferenceExpr,
    ReferenceInput,
    ReferenceResolver,
)

__all__ = [
    "COMMAND_SCHEMA_VERSION",
    "LEGACY_SCHEMA_VERSION",
    "PROTOCOL_VERSION",
    "ActorIdentity",
    "ArtifactPassport",
    "AuthorizationError",
    "Capability",
    "CapabilityDescription",
    "CapabilityError",
    "CapabilityRegistry",
    "CapabilitySnapshot",
    "CapabilityVersionError",
    "CommandBus",
    "CommandExecutionError",
    "CommandProvenance",
    "CommandResult",
    "CommandValidationError",
    "AssetRecord",
    "Clip",
    "DurableStore",
    "DurableStudioStore",
    "EffectLayerRef",
    "Domain",
    "EditTransaction",
    "ExecutionPolicy",
    "ExecutionPolicyError",
    "ExecutionProof",
    "IdempotencyConflictError",
    "IndependentMediaVerificationError",
    "InputRef",
    "InputReferenceError",
    "JobAttemptLease",
    "LeaseExpiredError",
    "Marker",
    "MediaRef",
    "NagarError",
    "OperationContext",
    "OperationOutcome",
    "OperationSpec",
    "PermissionDecision",
    "PermissionDeniedError",
    "PermissionLevel",
    "PlanExecutionResult",
    "PlanResult",
    "PlanTransaction",
    "Playhead",
    "PreconditionError",
    "Project",
    "ProjectAccess",
    "ProjectAuthorizer",
    "ProvenanceCausalChain",
    "ReferenceExpr",
    "ReferenceInput",
    "ReferenceResolutionError",
    "ReferenceResolver",
    "RequestContext",
    "StaleFencingTokenError",
    "TargetRef",
    "Timeline",
    "TimeBase",
    "TimeRangeUS",
    "Track",
    "TypedCommand",
    "UndoConflictError",
    "UndoStackEmptyError",
    "UnknownCapabilityError",
    "UnknownOperationError",
    "build_wave1_registry",
    "compute_parameters_hash",
    "compute_state_hash",
    "frame_number_for",
    "new_project",
    "verify_causal_provenance_chain",
    "verify_media_artifact_independently",
]
