"""Regression tests for the Alembic revision chain (D4).

The initial revision (47903d282ede) was autogenerated once, then hand-audited
for portability (SQLite + PostgreSQL/Neon).  These tests lock the invariants
that matter for a hand-edited migration:

1. ``alembic upgrade head`` on a fresh SQLite file creates the exact table set
   and index set derived from ``SQLModel.metadata``.
2. ``alembic downgrade base`` empties the schema again (nothing leaks).
3. ``alembic check`` reports zero drift — the schema the migration produces is
   equivalent to the current models.
4. The revision chain from ``base`` is a single line ending at head.

The tests drive Alembic's programmatic API with a fresh ``Config``, so they do
not depend on the developer's cwd or on a stray ``alembic.ini``.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine
from sqlmodel import SQLModel

import nexus_ai_agent.storage.db  # noqa: F401  (registers all models)
from nexus_ai_agent.config import settings as settings_module

_REPO_ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture(autouse=True)
def _clean_env(monkeypatch: pytest.MonkeyPatch) -> None:
    """Isolate migration runs from inherited env values and settings caches."""
    monkeypatch.delenv("NEXUS_DATABASE_URL", raising=False)
    monkeypatch.delenv("DATABASE_URL", raising=False)
    monkeypatch.delenv("NEXUS_DB_PATH", raising=False)
    settings_module.get_settings.cache_clear()
    yield
    settings_module.get_settings.cache_clear()


@pytest.fixture()
def db_path(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> str:
    """Point the migration URL at an isolated SQLite file in the test temp dir."""
    path = str(tmp_path / "migrations.sqlite")
    monkeypatch.setenv("NEXUS_DB_PATH", path)
    settings_module.get_settings.cache_clear()
    return path


def _make_config() -> Config:
    config = Config(str(_REPO_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(_REPO_ROOT / "migrations"))
    return config


def _expected() -> tuple[set[str], set[tuple[str, str, bool]]]:
    """The (tables, indexes) that SQLModel.metadata declares today."""
    tables: set[str] = set()
    indexes: set[tuple[str, str, bool]] = set()
    for tname, table in SQLModel.metadata.tables.items():
        tables.add(tname)
        pk_cols = {c.name for c in table.primary_key.columns}
        for index in table.indexes:
            cols = [c.name for c in index.columns]
            if len(cols) == 1 and cols[0] in pk_cols:
                # Single-column index mirroring the primary key: not emitted by
                # the revision (SQLModel does not request it as a real index).
                continue
            indexes.add((tname, index.name, bool(index.unique)))
    return tables, indexes


def _actual(db_file: str) -> tuple[set[str], set[tuple[str, str, bool]]]:
    engine = create_engine(f"sqlite:///{db_file}")
    with engine.connect() as conn:
        table_rows = conn.exec_driver_sql(
            "SELECT name FROM sqlite_master WHERE type='table'"
        ).fetchall()
        tables = {r[0] for r in table_rows if r[0] != "alembic_version"}
        index_rows = conn.exec_driver_sql(
            "SELECT name, tbl_name FROM sqlite_master WHERE type='index' "
            "AND name NOT LIKE 'sqlite_autoindex%'"
        ).fetchall()
        indexes: set[tuple[str, str, bool]] = set()
        for name, tbl_name in index_rows:
            per_table = conn.exec_driver_sql(f'PRAGMA index_list("{tbl_name}")').fetchall()
            uniq = any(r[1] == name and bool(r[2]) for r in per_table)
            indexes.add((tbl_name, name, uniq))
    return tables, indexes


def test_revision_chain_is_single_line() -> None:
    script = ScriptDirectory.from_config(_make_config())
    heads = script.get_heads()
    assert heads == ["f4a9c2e71b08"]
    assert [r.revision for r in script.walk_revisions()] == [
        "f4a9c2e71b08",
        "47903d282ede",
    ]


def test_lifecycle_migration_is_isolated_and_postgres_only() -> None:
    """f4a9c2e71b08: exactly one table, no other DDL, PG dialect only."""
    import re

    migration = (
        Path(__file__).parents[2]
        / "migrations"
        / "versions"
        / "f4a9c2e71b08_nexus_checkpoint_lifecycle.py"
    )
    source = migration.read_text(encoding="utf-8")
    # exactly one create / one drop, both the lifecycle table
    assert source.count("op.create_table(") == 1
    assert source.count("op.drop_table(") == 1
    assert '"nexus_checkpoint_lifecycle"' in source
    # no other DDL vocabulary
    lowered = source.lower()
    assert "op.execute(" not in lowered
    assert "create extension" not in lowered
    assert "pgvector" not in lowered
    assert "alter table" not in lowered
    # never touches a LangGraph table
    assert not re.search(r"\bcheckpoints\b", source)
    assert "checkpoint_writes" not in source
    assert "checkpoint_blobs" not in source
    # dialect guard in both directions
    assert source.count("if not _is_postgresql():") == 2


def test_upgrade_creates_exact_schema(db_path: str) -> None:
    command.upgrade(_make_config(), "head")
    assert _actual(db_path) == _expected()


def test_downgrade_empties_schema(db_path: str) -> None:
    config = _make_config()
    command.upgrade(config, "head")
    command.downgrade(config, "base")
    assert _actual(db_path) == (set(), set())


def test_no_drift_after_upgrade(db_path: str) -> None:
    config = _make_config()
    command.upgrade(config, "head")
    # Raises AutogenerateDiffsDetected if the migration diverges from models.
    command.check(config)


def test_upgrade_downgrade_upgrade_is_idempotent(db_path: str) -> None:
    config = _make_config()
    command.upgrade(config, "head")
    command.downgrade(config, "base")
    command.upgrade(config, "head")
    assert _actual(db_path) == _expected()


def test_check_detects_out_of_band_changes(db_path: str) -> None:
    """Guard the gate itself: an untracked schema change must be flagged."""
    config = _make_config()
    command.upgrade(config, "head")

    engine = create_engine(f"sqlite:///{db_path}")
    with engine.begin() as conn:
        conn.exec_driver_sql("CREATE TABLE stray_table (id INTEGER PRIMARY KEY)")

    with pytest.raises(AutogenerateDiffsDetected):
        command.check(config)


def test_base_migration_has_no_optional_extension_dependency() -> None:
    """The mandatory schema must remain usable on PostgreSQL without pgvector."""
    migration = Path(__file__).parents[2] / "migrations/versions/47903d282ede_initial_schema.py"
    source = migration.read_text(encoding="utf-8").lower()
    assert "create extension" not in source
    assert "pgvector" not in source
